# Generated by Django 5.0 on 2023-12-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                ("teacher_id", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="student_ac",
            fields=[
                ("paid", models.FloatField()),
                ("payable", models.FloatField()),
                (
                    "ac_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="students.student",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teacher_ac",
            fields=[
                ("balance", models.FloatField()),
                ("paid", models.FloatField()),
                (
                    "ac_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="teachers.teacher",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="transection_detail",
            fields=[
                ("trxdid", models.AutoField(primary_key=True, serialize=False)),
                ("admition_fee", models.FloatField()),
                ("tution_fee", models.FloatField()),
                ("exam_fee", models.FloatField()),
                ("computer_lab", models.FloatField()),
                ("student_activity_fee", models.FloatField()),
                ("library_fee", models.FloatField()),
                ("scout_fee", models.FloatField()),
                ("development_charge", models.FloatField()),
                ("id_card", models.FloatField()),
                ("fine", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="transection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trxid", models.CharField(max_length=25, unique=True)),
                ("amount", models.FloatField()),
                ("get_way", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ac_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.student_ac",
                    ),
                ),
                (
                    "trxdid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.transection_detail",
                    ),
                ),
            ],
        ),
    ]
