# Generated by Django 5.0 on 2023-12-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        ("students", "0002_alter_student_password"),
        ("teachers", "0002_alter_teacher_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transection_detail",
            old_name="admition_fee",
            new_name="admission_fee",
        ),
        migrations.AddField(
            model_name="transection_detail",
            name="total",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student_ac",
            name="ac_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacher_ac",
            name="ac_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="teachers.teacher",
            ),
        ),
    ]
