# Generated by Django 5.0 on 2023-12-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$eHc0j9tQKSleRoTPhMrjIA$VwKOONlJ0P8s5mpSnPT6J3MoJ7ZUiQyIAvCNoZRSRyY=",
                max_length=128,
            ),
        ),
    ]
