# Generated by Django 5.0 on 2024-01-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.AlterField(
            model_name="department",
            name="student_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
