# Generated by Django 5.0 on 2023-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "teacher_id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(default="", max_length=10, unique=True)),
                (
                    "password",
                    models.CharField(
                        default="pbkdf2_sha256$720000$3PRNnOijSNmorwcH3t9F9Q$vo9wH6OiqYRwDWjCV3iEAz0sdEh+j4tZ45LMA2YvQoE=",
                        max_length=128,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=6)),
                ("date_of_birth", models.DateField()),
                ("nid", models.CharField(max_length=17, unique=True)),
                ("father_name", models.CharField(max_length=150)),
                ("father_nid", models.IntegerField()),
                ("mother_name", models.CharField(max_length=150)),
                ("mother_nid", models.IntegerField()),
                ("phone_number", models.CharField(max_length=11)),
                ("present_address", models.CharField(max_length=500)),
                ("parmanent_address", models.CharField(max_length=500)),
                ("image", models.CharField(default="", max_length=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
