# Generated by Django 5.0 on 2023-12-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$2eQIUdV9YMOT0ThYBv3qiB$OBxmNvUmsDgt9fDVcH88d/f9c8EmSfgZGFXd/JKADuc=",
                max_length=128,
            ),
        ),
    ]
