# Generated by Django 5.0 on 2024-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_alter_teacher_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="password",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="username",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
